pull_request_rules: []
commands_restrictions:
  queue:
    conditions:
      - sender-permission >= write
merge_queue:
  mode: parallel
  max_parallel_checks: 1
scopes:
  source:
    files:
      all: {}
queue_rules:
  - name: default
    batch_size: 1
    queue_conditions: []
    merge_conditions:
      - check-success = @github-actions/vm6-mq-failed-tests
    max_checks_retries: 0
    merge_method: fast-forward
