pull_request_rules: []
commands_restrictions:
  queue:
    conditions:
      - sender-permission >= admin
merge_queue:
  mode: parallel
  max_parallel_checks: 2
scopes:
  source:
    manual:
queue_rules:
  - name: vm6-commentconfusion-261002
    queue_conditions: []
    merge_conditions:
      - check-success = vm6-commentconfusion-never-pass-261002
    batch_size: 1
    merge_method: merge
